### ISSUE TITLE
prelude/store.dhall-lang.org isn't updating

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-lang#1231] opened 2021-10-14 16:58 UTC
Opening an issue per discussion on Slack.  store.dhall-lang.org still is missing prelude v21 (and by extension prelude.dhall-lang.org is pointing to the old version), despite the new prelude having been added ~2 months ago in d44882ef5148590bd660cd8d90b0347a48c0825b

The server self-deployment may be borked?

**Comment by Gabriel439** [comment] 2021-10-16 03:52
Yeah, it turns out that something went wrong with `systemd`.  It was hanging when attempting to start some of the `acme-*.target` units as part of the system activation

I still don't know exactly what went wrong, but when debugging this I was able to minimize the problem down to the following `systemd` bug:

* I would run `systemctl start acme-finished-cache.dhall-lang.org.target` which only depended on `acme-cache.dhall-lang.org.service`
* `acme-cache.dhall-lang.org.service` would succeed, but `acme-finished-cache.dhall-lang.org.target` would still hang

With a mix of manually stopping and starting a few targets while debugging further the problem disappeared, so I'm chalking this up to a `systemd` bug which I can no longer reproduce 🤷🏼‍♀️ 

Either way, store.dhall-lang.org is fixed now, so I'll close this

**Closed by Gabriel439** 2021-10-16 03:52 UTC
