### ISSUE TITLE
`dhall-lang.org` domain down? I can't access Discourse or Prelude

### ISSUE THREAD

**Issue by isaacsanders** [dhall-lang/dhall-lang#1268] opened 2022-01-21 19:39 UTC

**Comment by moinessim** [comment] 2022-01-21 20:06
Can't access dhall's nix binary cache https://cache.dhall-lang.org either...

**Comment by isaacsanders** [comment] 2022-01-21 20:19
This is still not resolving for us (from dhall-render) https://prelude.dhall-lang.org/v16.0.0/Text/concatSep

**Comment by isaacsanders** [comment] 2022-01-21 20:21
It's back now

**Comment by isaacsanders** [comment] 2022-01-21 20:27
This works now.

**Comment by SebastianKG** [comment] 2022-01-21 20:35
Service is intermittent now, I still can't build my project because one of several Prelude dependencies will break.

**Comment by Gabriel439** [comment] 2022-01-21 20:53
I can reproduce the failure.  I'm looking into it

**Comment by Gabriel439** [comment] 2022-01-21 21:05
Here's what I'm seeing in the logs for a sample slow request to fetch one of the Prelude imports:

```
Jan 21 21:00:23 dhall-lang nginx[2473]: 2022/01/21 21:00:23 [error] 2473#2473: *2267 upstream timed out (110: Connection timed out) while connecting to upstream, client: 2601:646:8700:6810:817e:45df:84a8:adc6, server: prelude.dhall-lang.org, request: "GET /Text/shell-escape.dhall HTTP/2.0", upstream: "https://[2606:50c0:8002::154]:443/dhall-lang/dhall-lang/v21.1.0/Prelude/Text/shell-escape.dhall", host: "prelude.dhall-lang.org"
```

That request is forwarding to an upstream URL which is the GitHub URL for the raw text.  However, a direct `curl` against the upstream URL is snappy, so it's likely an issue with `nginx`.

**Comment by Gabriel439** [comment] 2022-01-21 21:16
So it's definitely not due to machine load.  I shut off all of the CPU/memory-intensive services (basically only `hydra`) and the system is fairly quiet, but I'm still seeing timeouts

**Comment by Gabriel439** [comment] 2022-01-21 21:20
It's also not due to any recent upgrades to the system.  I rolled back to a known good configuration and the problem still persists

**Comment by SebastianKG** [comment] 2022-01-21 21:22
Could there be a machine within a load balancer that is failing? I notice that when I refresh e.g. prelude.dhall-lang.org/v20.1.0/Map/keyText, I get a slow load after 1-in-5-ish tries

**Comment by Gabriel439** [comment] 2022-01-21 21:25
Yeah, the timeout is intermittent, but there is no load balancer on dhall-lang.org; it's just a single `nginx` reverse proxy which fronts each of the subdomains

The two current hypotheses I have right now are:

* There is some client that is hammering the `nginx` server on dhall-lang.org that is adding undue load
* There's something wrong with Linode's networking infrastructure (since that's where the server is hosted)

**Comment by Gabriel439** [comment] 2022-01-21 21:27
Actually, both of those hypotheses are probably wrong because other subdomains (like discourse.dhall-lang.org) resolve just fine

**Comment by Gabriel439** [comment] 2022-01-21 21:32
For reference, here is the NixOS configuration for `nginx`:

https://github.com/dhall-lang/dhall-lang/blob/609653f9669e1cabc88b6838d18f093b5d91ee42/nixops/logical.nix#L168-L394

… and here is the materialized `nginx.conf` that it generates:

<details>
```
pid /run/nginx/nginx.pid;
error_log stderr;
daemon off;
events {
}
http {
	# The mime type definitions included with nginx are very incomplete, so
	# we use a list of mime types from the mailcap package, which is also
	# used by most other Linux distributions by default.
	include /nix/store/rya2s79k5ncqbas09rwhq43lrbr4s3m0-mailcap-2.1.52/etc/nginx/mime.types;
	include /nix/store/p55kz2gq4kfc4y82fmm408iyv1mjrwi3-nginx-1.20.1/conf/fastcgi.conf;
	include /nix/store/p55kz2gq4kfc4y82fmm408iyv1mjrwi3-nginx-1.20.1/conf/uwsgi_params;
	default_type application/octet-stream;
	# optimisation
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 4096;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	# Keep in sync with https://ssl-config.mozilla.org/#server=nginx&config=intermediate
	ssl_session_timeout 1d;
	ssl_session_cache shared:SSL:10m;
	# Breaks forward secrecy: https://github.com/mozilla/server-side-tls/issues/135
	ssl_session_tickets off;
	# We don't enable insecure ciphers by default, so this allows
	# clients to pick the most performant, per https://github.com/mozilla/server-side-tls/issues/260
	ssl_prefer_server_ciphers off;
	# OCSP stapling
	ssl_stapling on;
	ssl_stapling_verify on;
	gzip on;
	gzip_proxied any;
	gzip_comp_level 5;
	gzip_types
	application/atom+xml
	application/javascript
	application/json
	application/xml
	application/xml+rss
	image/svg+xml
	text/css
	text/javascript
	text/plain
	text/xml;
	gzip_vary on;
	# $connection_upgrade is used for websocket proxying
	map $http_upgrade $connection_upgrade {
		default upgrade;
		''      close;
	}
	client_max_body_size 10m;
	server_tokens off;
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name cache.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name cache.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/cache.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/cache.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/cache.dhall-lang.org/chain.pem;
		location / {
			proxy_pass http://127.0.0.1:5000;
		}
	}
	server {
		listen 0.0.0.0:80 default_server ;
		listen [::]:80 default_server ;
		server_name dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 default_server ;
		listen [::]:443 ssl http2 default_server ;
		server_name dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/dhall-lang.org/chain.pem;
		location / {
			index index.html;
			root /nix/store/y7saag7xldg9lwh5nyzrlv9954mnqsh2-try-dhall;
		}
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name discourse.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name discourse.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/discourse.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/discourse.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/discourse.dhall-lang.org/chain.pem;
		location / {
			proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock;
		}
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header Accept-Encoding "";
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name docs.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name docs.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/docs.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/docs.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/docs.dhall-lang.org/chain.pem;
		location / {
			index index.html;
			root /nix/store/skwn2jnb6ixr6fhzswnhr0sl9aizq1yf-docs;
		}
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name hydra.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name hydra.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/hydra.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/hydra.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/hydra.dhall-lang.org/chain.pem;
		location / {
			proxy_pass http://127.0.0.1:3000;
		}
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Server $host;
		proxy_set_header Accept-Encoding "";
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name mail.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name mail.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/mail.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/mail.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/mail.dhall-lang.org/chain.pem;
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name prelude.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name prelude.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/prelude.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/prelude.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/prelude.dhall-lang.org/chain.pem;
		location / {
			proxy_pass https://raw.githubusercontent.com;
			if ($request_method = 'OPTIONS') {
				add_header 'Access-Control-Allow-Origin' "*";
				add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
				add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
				add_header 'Access-Control-Max-Age' 600;
				add_header 'Content-Type' 'text/plain; charset=utf-8';
				add_header 'Content-Length' 0;
				return 204;
			}
			if ($request_method = 'GET') {
				add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
				add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
				add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
			}
			rewrite ^/?$ https://store.dhall-lang.org/Prelude-v21.1.0 redirect;
			rewrite ^/(v[^/]+)$ https://github.com/dhall-lang/dhall-lang/tree/$1/Prelude redirect;
			rewrite ^/(v[^/]+)/(.*)$ /dhall-lang/dhall-lang/$1/Prelude/$2 break;
			rewrite ^/(.*)$ /dhall-lang/dhall-lang/v21.1.0/Prelude/$1 break;
		}
	}
	server {
		listen 0.0.0.0:80 ;
		listen [::]:80 ;
		server_name store.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		location / {
			return 301 https://$host$request_uri;
		}
	}
	server {
		listen 0.0.0.0:443 ssl http2 ;
		listen [::]:443 ssl http2 ;
		server_name store.dhall-lang.org ;
		location /.well-known/acme-challenge {
			root /var/lib/acme/acme-challenge;
			auth_basic off;
		}
		ssl_certificate /var/lib/acme/store.dhall-lang.org/fullchain.pem;
		ssl_certificate_key /var/lib/acme/store.dhall-lang.org/key.pem;
		ssl_trusted_certificate /var/lib/acme/store.dhall-lang.org/chain.pem;
		location / {
			index index.html;
			root /nix/store/25x1rgh808iqzginmxin2c6k394hyknq-store;
		location ~ "^/1220[[:xdigit:]]{64}$" {
			default_type application/dhall+cbor;
		}
	}
}
server {
	listen 0.0.0.0:80 ;
	listen [::]:80 ;
	server_name test.dhall-lang.org ;
	location /.well-known/acme-challenge {
		root /var/lib/acme/acme-challenge;
		auth_basic off;
	}
	location / {
		return 301 https://$host$request_uri;
	}
}
server {
	listen 0.0.0.0:443 ssl http2 ;
	listen [::]:443 ssl http2 ;
	server_name test.dhall-lang.org ;
	location /.well-known/acme-challenge {
		root /var/lib/acme/acme-challenge;
		auth_basic off;
	}
	ssl_certificate /var/lib/acme/test.dhall-lang.org/fullchain.pem;
	ssl_certificate_key /var/lib/acme/test.dhall-lang.org/key.pem;
	ssl_trusted_certificate /var/lib/acme/test.dhall-lang.org/chain.pem;
	location / {
		proxy_pass https://raw.githubusercontent.com;
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
			add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
			add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		rewrite ^/?$ https://store.dhall-lang.org/Prelude-v21.1.0 redirect;
		rewrite ^/(v[^/]+)$ https://github.com/dhall-lang/dhall-lang/tree/$1/Prelude redirect;
		rewrite ^/(v[^/]+)/(.*)$ /dhall-lang/dhall-lang/$1/Prelude/$2 break;
		rewrite ^/(.*)$ /dhall-lang/dhall-lang/v21.1.0/Prelude/$1 break;
	}
	location /bar {
		if ($http_test = "") {
			return 403;
		}
		return 200 'True';
	}
	location /cors/AllowedAll.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/Empty.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/NoCORS.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/Null.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "null";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "null";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/OnlyGithub.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "raw.githubusercontent.com";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "raw.githubusercontent.com";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/OnlyOther.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "example.com";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "example.com";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/OnlySelf.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "test.dhall-lang.org";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "test.dhall-lang.org";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "42";
	}
	location /cors/SelfImportAbsolute.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "https://test.dhall-lang.org/cors/NoCORS.dhall";
	}
	location /cors/SelfImportRelative.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "./NoCORS.dhall";
	}
	location /cors/TwoHopsFail.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "https://raw.githubusercontent.com/dhall-lang/dhall-lang/5ff7ecd2411894dd9ce307dc23020987361d2d43/tests/import/data/cors/OnlySelf.dhall";
	}
	location /cors/TwoHopsSuccess.dhall {
		add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Max-Age' 600;
			add_header 'Content-Type' 'text/plain; charset=utf-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		if ($request_method = 'GET') {
			add_header 'Access-Control-Allow-Origin' "*";
			add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
		}
		echo "https://raw.githubusercontent.com/dhall-lang/dhall-lang/5ff7ecd2411894dd9ce307dc23020987361d2d43/tests/import/data/cors/OnlyGithub.dhall";
	}
	location /foo {
		if ($http_test = "") {
			return 403;
		}
		return 200 './bar';
	}
	location /random-string {
		set_secure_random_alphanum $res 32;
		echo $res;
	}
}
}
```
</details>

**Comment by isaacsanders** [comment] 2022-01-21 21:49
What would a project to move prelude to a CDN look like?

**Comment by isaacsanders** [comment] 2022-01-21 21:51
Or even a GitHub pages situation. I'd hate for the userbase to knock over your Linode, when we have options like Github or Fastly. (Fastly hosts hex.pm for free, maybe they would do the same for dhall)

**Comment by Gabriel439** [comment] 2022-01-21 21:59
The Prelude is already hosted on GitHub.  The only thing that the `nginx` proxy is doing is providing a nicer domain name and enabling CORS, so any service that can do that could easily replace the current reverse proxy

**Comment by Gabriel439** [comment] 2022-01-21 22:00
Also, it's worth pointing out that because the Prelude is hosted on GitHub, affected projects can temporarily work around the issue by using the raw GitHub URL (e.g. https://raw.githubusercontent.com/dhall-lang/dhall-lang/master/Prelude/package.dhall)

**Comment by isaacsanders** [comment] 2022-01-21 22:05
> The Prelude is already hosted on GitHub. The only thing that the `nginx` proxy is doing is providing a nicer domain name and enabling CORS, so any service that can do that could easily replace the current reverse proxy

Github supports the nice domain name thing already, right?

**Comment by Gabriel439** [comment] 2022-01-21 22:06
GitHub does support custom domains for GitHub pages, but I don't know if it supports a custom domain that passes through requests to https://raw.githubusercontent.com/dhall-lang/dhall-lang/master/Prelude

**Comment by Gabriel439** [comment] 2022-01-21 22:31
Trying to further narrow this down:

The following command is reliably snappy when run directly on the dhall-lang.org machine:

```ShellSession
$ curl https://raw.githubusercontent.com/dhall-lang/dhall-lang/master/Prelude/package.dhall
```

… whereas the corresponding command against `nginx` on the same machine sometimes times out:

```ShellSession
$ curl --header 'Host: prelude.dhall-lang.org' --insecure https://localhost/package.dhall
```

Furthermore, querying https://prelude.dhall-lang.org (no `/package.dhall`) is also snappy, since it redirects to store.dhall-lang.org instead of GitHub.

So it seems that something about using GitHub as the upstream server is responsible for this issue

**Comment by Gabriel439** [comment] 2022-01-21 22:45
Okay, I think I'm closer to figuring out the problem.  My hypothesis is that the timeout happens when `nginx` resolves raw.githubusercontent.com to an IPv6 address instead of an IPv4 address.  It does eventually time out and fall back to IPv4 when this happens but not quickly enough, which is what leads to these timeouts.  The timeouts are random because `nginx` randomly decides to use IPv6 some fraction of the time.  `curl` didn't have this issue because it falls back to IPv4 much more quickly than `nginx` does

I'm currently testing this hypothesis right now

**Comment by Gabriel439** [comment] 2022-01-21 23:17
Yeah, that is exactly what is going on:

```ShellSession
$ host raw.githubusercontent.com
raw.githubusercontent.com has address 185.199.109.133
raw.githubusercontent.com has address 185.199.110.133
raw.githubusercontent.com has address 185.199.111.133
raw.githubusercontent.com has address 185.199.108.133
raw.githubusercontent.com has IPv6 address 2606:50c0:8001::154
raw.githubusercontent.com has IPv6 address 2606:50c0:8002::154
raw.githubusercontent.com has IPv6 address 2606:50c0:8003::154
raw.githubusercontent.com has IPv6 address 2606:50c0:8000::154

$ # This succeeds:
$ curl --header 'Host: raw.githubusercontent.com'  --insecure 'https://185.199.109.133/dhall-lang/dhall-lang/v21.0.0/Prelude/List/map.dhall'

$ # This times out:
$ curl --header 'Host: raw.githubusercontent.com'  --insecure 'https://[2606:50c0:8002::154]/dhall-lang/dhall-lang/v21.0.0/Prelude/List/map.dhall'
```

Now I just need to figure out how to get `nginx` to not use IPv6 when connecting to the upstream server to work around the issue for now.

**Comment by Gabriel439** [comment] 2022-01-21 23:19
Also, the IPv6 `curl` command fails even on my local machine, so it looks like something about GitHub's IPv6 support recently broke, which is why this only just started happening recently.  As soon as I get this resolved I'll try to figure out how to report the issue upstream

**Comment by isaacsanders** [comment] 2022-01-21 23:32
Thank you for your response on this. I’ve only just started using Dhall, but it is very nice to use.

**Comment by Gabriel439** [comment] 2022-01-21 23:44
Alright, I think I was able to work around the problem by disabling IPv6 on dhall-lang.org.  If people can verify that things are fixed on their end then I can put up a pull request for the fix

**Comment by Gabriel439** [comment] 2022-01-22 00:44
Fix is up here: https://github.com/dhall-lang/dhall-lang/pull/1269

**Comment by Gabriel439** [comment] 2022-01-22 00:46
Actually, it looks like whatever upstream issue with GitHub there was has gone away.  The IPv6 `curl` commands now succeed …

**Comment by SebastianKG** [comment] 2022-01-22 19:32
@Gabriel439 I've had a chance to validate the change, and I can confirm that it works for me. Thank you for your hard work on such short notice. Dhall is a lot of fun to use, and I'm amazed by all the work you've put in.

I am interested in pursuing changes that will help safeguard against any other unexpected downtime in the future, however unlikely--if there could be a way to redirect all dependencies to a different host (e.g. if one repository on Git points to another repository on a personal server which points to prelude.dhall-lang, have a flag which allows me to replace all the hosts with my S3 root or something). Another solution (which I could potentially give a shot) is to have a published, pre-made Dhall cache (à la LTS Haskell in some ways) for the entire dependency tree of the awesome-dhall packages, and then I would run my `coralogix/dhall-concourse`-described CI in isolation from any networking with that cache pre-loaded.

I can potentially make a separate issue for this topic following up on whichever path you feel makes sense.

**Comment by Gabriel439** [comment] 2022-01-22 20:43
I think the solution that would work best is a public cache, because if the imports are protected by integrity checks then the public cache can still satisfy them even if the underlying import is unavailable.  Indeed, `missing sha256:…` will resolve successfully so long as the cache has an import matching the hash

**Comment by Gabriel439** [comment] 2022-01-22 21:22
Also, currently we do currently having the initial pieces for infrastructure supporting a public cache.  `store.dhall-lang.org` not only serves documentation, but also cache products for all packages hosted on there.  For example, `https://store.dhall-lang.org/1220${HASH}` will serve the binary cache product for a package whose hash is `sha256:${HASH}`

The only thing is missing is to add client-side support for optionally using that cache

**Comment by Gabriel439** [comment] 2022-01-22 21:37
So I will need to restart the server in an attempt to re-enable IPv6 since I believe the upstream issue with GitHub is fixed.  If the issue comes back I'll revert back to disabling IPv6

**Comment by Gabriel439** [comment] 2022-01-22 21:56
It looks like re-enabling IPv6 in general reintroduced the problem, so I came up with a different solution.

So it looks like #1269 is not a good solution because it forbids incoming IPv6 requests, too.  So, for example, `curl --ipv6 https://dhall-lang.org` would no longer work

However, I was able to disable IPv6 just for `nginx`'s DNS resolution, which fixed the problem a little better, albeit at the expense of a hacky workaround: https://github.com/dhall-lang/dhall-lang/pull/1270

**Comment by Gabriel439** [comment] 2022-01-31 16:03
It looks like there are still lingering issues here that affect our CI.  I'll reopen this until those are fixed

There may be some downtime as I might need to reboot the server a few times to test some changes

**Closed** 2022-02-01 16:43 UTC
