### ISSUE TITLE
dhall format removes comments

### ISSUE THREAD

**Issue by jsamsa** [dhall-lang/dhall-lang#798] opened 2019-10-30 17:28 UTC
When the dhall format command is run all comments are removed from source. One advantage dhall has over a format like json is the ability to comment the source. Having the formatter respect comments would be a nice feature.

$ dhall format 
{ -- this is a comment
 greeting = "hello"
}
^D
{ greeting = "hello" }

**Comment by sjakobi** [comment] 2019-10-30 17:36
Duplicate of https://github.com/dhall-lang/dhall-haskell/issues/145.

See https://github.com/dhall-lang/dhall-haskell/issues/145#issuecomment-527223566 for the progress made so far.

**Closed by sjakobi** 2019-10-30 17:36 UTC
