### ISSUE TITLE
`Dhall.Marshall.Decode.list` does not include `ListAppend`

### ISSUE THREAD

**Issue by JordanMartinez** [dhall-lang/dhall-lang#1217] opened 2021-08-28 21:18 UTC
[`list`](https://hackage.haskell.org/package/dhall-1.40.1/docs/src/Dhall.Marshal.Decode.html#list) only parses `ListLit`s. It does not include `ListAppend`.

Since there may be times where one only wants a `ListLit` and not a `ListAppend`, I propose adding another combinator called `listAll` that parses both `ListLit`s and `ListAppend`s. The below implementation (based on `list`) works but is not stack-safe:
```haskell
-- |
-- Like `Dhall.list` but it parses `ListAppend`s as well.
listAll :: Dhall.Decoder a -> Dhall.Decoder [a]
listAll (Dhall.Decoder extractIn expectedIn) = Dhall.Decoder extractOut expectedOut
  where
    extractOut (Dhall.ListLit _ es) = Data.Foldable.toList <$> traverse extractIn es
    extractOut (Dhall.ListAppend l r) = (++) <$> extractOut l <*> extractOut r
    extractOut expr           = Dhall.typeError expectedOut expr

    expectedOut = Dhall.App Dhall.List <$> expectedIn
```

**Comment by Gabriel439** [comment] 2021-08-28 21:34
Can you give an example of a Dhall expression that you'd like to decode using this change?  The reason I ask is because my understanding is that if the expression is decodable then there won't be a `ListAppend` in the final result, because it will be β-normalized

**Comment by JordanMartinez** [comment] 2021-08-28 22:26
Hm... Maybe the real issue I'm experiencing is that [`Spago` is not calling `normalize` here](https://github.com/purescript/spago/blob/master/src/Spago/Config.hs#L121-L124) before we parse the expression, which I assume would convert `ListAppend`s into regular `ListLit`s. Is that correct?

**Comment by JordanMartinez** [comment] 2021-08-28 22:45
Ah, nevermind. I misread an issue. This does work without calling `normalize`. The issue was related to something else. Sorry about that.

**Comment by Gabriel439** [comment] 2021-08-28 22:52
Hmmm.  Spago shouldn't have to normalize the expression because `inputExpr` should be doing that automatically.

Do you have a minimal reproducing example?  Also, what is the exact error message you are getting?

**Comment by Gabriel439** [comment] 2021-08-28 22:53
Oh, alright.  Then I'll close this back again

**Closed by Gabriel439** 2021-08-28 22:53 UTC

**Comment by f-f** [comment] 2021-08-29 13:36
@Gabriel439 there are some places in Spago where we want to manipulate Dhall AST (e.g. to add an element to a list), but do not want to normalize in order to keep imports intact - as normalizing would inline them

**Comment by sjakobi** [comment] 2021-09-01 15:26
If we start supporting denormalized inputs in `list`, where do we stop?!

As an analogy, should `bool` support expressions with `&&` and `||`? What about record selections for `Bool` fields?

I don't think that going down this route would be sustainable. If Spago can't use vanilla β-normalization, I think it should try to manipulate the AST in a way that it becomes digestible for the decoders.
