### ISSUE TITLE
Support nested record syntax ala nix?

### ISSUE THREAD

**Issue by arianvp** [dhall-lang/dhall-lang#220] opened 2018-08-20 11:53 UTC
Would be nice if

```
{ a.b.c.d =  0 } 
```

would translate to

```
{ a = { b = { c  = {d = 0 }}}}
```

Just like in the Nix language.

It would help us a lot for:

https://github.com/dhall-lang/dhall-kubernetes/issues/11

**Comment by Gabriel439** [comment] 2018-08-23 03:55
Sorry for the delay, I just needed some time to think about this.

I'm going to give a tentative yes on this, but I won't know for sure until I try to implement it.  Here is my rough sketch of how this would be standardized.

The interesting case to handle is this one (which Nix misbehaves on):

```
$ nix-instantiate --eval --expr '{ x.y = 1; x.z = 2; }'
{ x = <CODE>; }

$ nix-instantiate --eval --expr '{ x.y = 1; x = { z = 2; }; }'
error: attribute 'x' at (string):1:12 already defined at (string):1:3
```

I think Dhall can gracefully accept both forms as valid by:

* specifying that `x.y = e` must always be equivalent `x = { y = e }`
* specifying that if a field is defined multiple times within the same record then you merge the multiple definitions with `∧` (with the normal type-checking rules for `∧`).  In other words:

```haskell
{ x = e₀, x = e₁ } = { x = e₀ ∧ e₁ }
```

This would imply a change to the semantics of how Dhall handles duplicate fields.  Previously Dhall would always reject them and this change would imply that Dhall would accept duplicate fields if they could be recursively merged.  Or in other words:

```haskell
{ x = 1, x = 2 }  -- Still invalid: `1 ∧ 2` does not type-check

{ x = { y = 1 }, x = 2 }  -- Still invalid: `{ y = 1 } ∧ 2` does not type-check

{ x = { y = 1 }, x = { z = 1 } } = { x = { y = 1, z = 1 } }  -- Newly valid
```

That actually seems like a reasonable thing to do even in the absence of support for `x.y.z` fields and could be standardized first by itself.

For implementation, this would require changing the record type and record literal representations to use `[Text]` for the keys instead of `Text`.  I'd have to actually try to implement it to see how difficult that change is.

The other thing to consider is whether `dhall format` or `dhall lint` should be opinionated about which field syntax to use.  In other words, should it prefer this:

```haskell
{ x.y = 1, x.z = 2 }
```

... or this:

```haskell
{ x = { y = 1, z = 2 } }
```

... or should it preserve the original syntax that the user used?

**Comment by arianvp** [comment] 2018-08-23 13:58
I think it should preserve the original syntax the user used.  In nix, people usually group stuff together:

```
{
   # get stuff done for yubi
    hardware.u2f.enable = true;
    services.yubikey.enable = true;

   # Nginx
   fireWall.blah = x;
   services.nginx.enable = true;
}
```

We wouldn't want to refactor that to
```
services =  {  nginx = { ... } ; yubikey = { } };
```

because it's unclear where the comment should go, etc.

**Comment by Gabriel439** [comment] 2018-08-23 16:55
@arianvp: Yeah, that seems like the right approach to me for formatting

However, one thing to keep in mind is that normalization would probably still expand out chained fields.  In other words, this:

```haskell
{ x.y = 1 }
```

... would normalize to:

```haskell
{ x = { y = 1 } }
```

There are two main reasons why I suggest this:

* Equivalence checking wouldn't require any modifications since β-reduction would handle normalizing records to a canonical form
* Semantic integrity checks would remain insensitive to refactoring fields in this way since they also are computed post-β-reduction

**Comment by Gabriel439** [comment] 2018-08-31 03:13
I ran into issues keeping the Haskell implementation efficient while trying to implement this.  The root of the problem is that there wasn't a good data structure available that allowed duplicate keys and also efficient lookup/union/intersection operations.

I'll probably postpone working on this for now, although I still think it's a good idea.  If somebody else can figure out an efficient way to do this I'd accept the pull request.

As far as standardization goes, this is pretty easy to standardize.  It's mainly the implementation that's tricky without sacrificing efficiency.

**Comment by Profpatsch** [comment] 2018-08-31 10:54
@Gabriel439 I was in need of something similar: https://github.com/Profpatsch/yarn-lock/blob/master/src/Data/MultiKeyedMap.hs, though in that case I didn’t need union and intersection, so I haven’t tried to implement it.

Though I agree with @f-f, I found the “feature” in nixpkgs too confusing to understand for the minor amount of boilerplate they safe. Plus they need a major design decision as you have noticed above (whether to merge recursively or abort). I nearly always opt for explicit braces in the nix code I write, it usually gives better visual flow and structural clarity, which makes the code more uniform and thus easier to read.

**Comment by Gabriel439** [comment] 2018-08-31 13:59
@f-f: Yeah, you're right.  This doesn't save that many characters (it's only a constant-factor improvement) and it is multiple ways to do the same thing.

**Comment by Gabriel439** [comment] 2018-08-31 14:01
@Profpatsch: Yeah, plus my reasoning was that if it was tricky for me to implement then it would also be tricky for other language bindings to efficiently implement, too

**Comment by f-f** [comment] 2018-10-31 11:30
It sounds like we agreed that having this would be "another way of doing things" - and we'd like to minimize them, especially if they don't save many characters.

So I'll close this for now, but let's reopen if we want to re-evaluate this

**Comment by Gabriel439** [comment] 2020-01-19 18:56
Reopening this in light of the discussion here: https://github.com/dhall-lang/dhall-lang/issues/754#issuecomment-575947214

Essentially: this combined with support for a deep override keyword (e.g. `with`) would essentially support for lens-like updates:

```haskell
example with { x.y.z = 1 }
```

**Comment by Gabriel439** [comment] 2020-02-01 05:47
The proposal for this is up here: https://github.com/dhall-lang/dhall-lang/pull/901

**Closed** 2020-02-05 03:15 UTC
