### ISSUE TITLE
Combine 'compilers' and interpreter?

### ISSUE THREAD

**Issue by jml** [dhall-lang/dhall-lang#7] opened 2017-09-08 08:48 UTC
I wonder if it would be more discoverable if there were just one `dhall` command. If run without options, it is the interpreter, and if run with `dhall --to-json` it compiles to JSON. WDYT?

**Comment by Gabriel439** [comment] 2017-09-08 13:55
The main downside that I can think of is that this forces all of the future Dhall compilers to be written in Haskell so that they can be bundled into the blessed executable.  A lesser downside is that the binary size will grow as we add more compilers to different formats (and I do plan to add a lot more; they are very easy to roll out)

In practice, that's already the current state of things because there's only one implementation of Dhall in Haskell.  However, I'm in the process of standardizing the language to support other implementations and even without the standard some other language bindings are pretty close to completion (most notably the Rust implementation, which could end up being faster than the Haskell implementation)

**Comment by jml** [comment] 2017-09-08 14:31
Hmm. Good point. Maybe a git-style subcommand system (where `dhall-json` gets executed when user runs `dhall json`)?

**Comment by Gabriel439** [comment] 2017-09-08 14:43
Yeah, I think that would work, especially if came bundled with an officially endorsed set of plugins and the `--help` output made it easy to discover what plugins were already installed

Keep in mind that I might not get to this for a while, but I'll try to implement this when I can

**Comment by jml** [comment] 2017-09-08 14:45
No worries at all re timeline. Am grateful for whatever you can manage. :)

**Comment by ocharles** [comment] 2019-08-01 20:35
Do we still want to do this?

**Comment by Gabriel439** [comment] 2019-08-02 03:45
I'll close this one out as a duplicate of https://github.com/dhall-lang/dhall-haskell/issues/1102 since splitting out the Dhall API from the executable is the main blocker for doing something like this

**Closed by Gabriel439** 2019-08-02 03:45 UTC
