### ISSUE TITLE
Sort/hashOf Builtin (or Kind/hashOf?)

### ISSUE THREAD

**Issue by jcdickinson** [dhall-lang/dhall-lang#1280] opened 2022-02-25 03:31 UTC
Being able to determine the hash of something could be really useful for lazy evaluation scenarios. Taking Nix as an example, this expression ultimately evaluates to "something" containing the hash of the bash derivation: `${bash}/bin/bash`.

Something similar could be done in Dhall with something along the lines of this overly simplified example:

```
let bash = https://...
in "/nix/store/${Sort/hashOf bash}/bash/bin"
```

This function would presumably normalize anything that it has been passed, effectively acting like `dhall hash`.

**Comment by f-f** [comment] 2022-02-25 08:08
Is this a duplicate of #739?

**Comment by jcdickinson** [comment] 2022-02-25 13:08
Yes, my search skills failed me.

**Closed** 2022-02-25 13:08 UTC
